name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pip=23.3.1
  - scikit-learn=1.3.2
  - jupyterlab=4.1.3
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - ydata-profiling==4.7.0  # Due to an error when importing pandas_profiling
      - ipywidgets==8.0.4  # Error: widget model not found (https://stackoverflow.com/questions/73715821/jupyter-lab-issue-displaying-widgets-javascript-error)
