name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - gcc  # ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found
  - gxx  # ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found
  - pip=23.3.1
  - pip:
      - requests==2.24.0
      - scikit-learn==1.3.2
      - mlflow==2.8.1
      - wandb==0.16.0
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
